Remove redundant sh quoting

diff --git a/bin/bzwc b/bin/bzwc
--- a/bin/bzwc
+++ b/bin/bzwc
@@ -5,9 +5,9 @@
 #
 
 Fatal() {
-	printf '%s: %s\n' "${0##*/}" "${*}" >&2
+	printf '%s: %s\n' "${0##*/}" "$*" >&2
 	exitstatus=2
-	exit ${exitstatus}
+	exit $exitstatus
 }
 
 . push.sh
@@ -17,56 +17,56 @@ process=
 exitstatus=0
 Cleanup() {
 	trap : EXIT HUP INT TERM
-	for cleani in ${process}
-	do	kill "${cleani}"
+	for cleani in $process
+	do	kill "$cleani"
 	done
 	process=
-	[ -n "${tempdir:++}" ] && test -d "${tempdir}" && rm -rf -- "${tempdir}"
+	[ -n "${tempdir:++}" ] && test -d "$tempdir" && rm -rf -- "$tempdir"
 	tempdir=
 	trap - EXIT HUP INT TERM
-	exit ${exitstatus}
+	exit $exitstatus
 }
 trap Cleanup EXIT HUP INT TERM
 
 MkTemp() {
 	[ -n "${tempdir:++}" ] && return
 	tempdir=`umask 077 && mktemp -d "/tmp/${0##*/}.XXXXXXXX"` && \
-		[ -n "${tempdir:++}" ] && test -d "${tempdir}" || \
+		[ -n "${tempdir:++}" ] && test -d "$tempdir" || \
 		Fatal 'cannot create temporary directory'
 }
 
 RunFifo() {
-	fifo=${1}
+	fifo=$1
 	e='1'
 	shift
 	MkTemp
-	fifo="${tempdir}/${fifo}"
-	while n="${fifo}(${e})" && test -r "${n}"
-	do	e=$(( ${e} + 1 ))
+	fifo=$tempdir/$fifo
+	while n=$fifo($e) && test -r "$n"
+	do	e=$(( $e + 1 ))
 	done
-	fifo=${n}
-	mkfifo -- "${fifo}" || Fatal "cannot create fifo ${fifo}"
-	Push wc "${fifo}"
-	"${@}" >"${fifo}" &
-	[ ${?} -eq 0 ] && process="${process} ${!}" \
-		|| Fatal "error executing ${*} >${fifo}"
+	fifo=$n
+	mkfifo -- "$fifo" || Fatal "cannot create fifo $fifo"
+	Push wc "$fifo"
+	"$@" >"$fifo" &
+	[ $? -eq 0 ] && process="$process ${!}" \
+		|| Fatal "error executing $* >$fifo"
 }
 
 PushFile() {
 	nofile=false
 	typ=
-	case `LC_ALL='C' file -- "${1}"` in
-	"${1}: bzip"*)
+	case `LC_ALL='C' file -- "$1"` in
+	"$1: bzip"*)
 		typ=bzcat;;
-	"${1}: gzip"*)
+	"$1: gzip"*)
 		typ=zcat;;
-	"${1}: lzma"*)
+	"$1: lzma"*)
 		typ=lzcat;;
-	"${1}: xz"*)
+	"$1: xz"*)
 		typ=xzcat;;
 	esac
 	if [ -z "${typ:++}" ]
-	then	case ${1} in
+	then	case $1 in
 		*.[lL][zZ][mM][aA])
 			typ=lzcat;;
 		*.[xX][zZ])
@@ -74,8 +74,8 @@ PushFile() {
 		esac
 	fi
 	if [ -z "${typ:++}" ]
-	then	Push wc "${1}"
-	else	RunFifo "${1##*/}" ${typ} -- "${1}"
+	then	Push wc "$1"
+	else	RunFifo "${1##*/}" $typ -- "$1"
 	fi
 }
 
@@ -84,34 +84,34 @@ remainder=false
 redirect=false
 nofile=:
 for i
-do	case ${i} in
+do	case $i in
 	-)
-		Push wc "${i}"
+		Push wc "$i"
 		redirect=:;;
 	--)
-		Push wc "${i}"
+		Push wc "$i"
 		remainder=:;;
 	-*)
-		if ${remainder}
-		then	PushFile "${i}"
-		else	Push wc "${i}"
+		if $remainder
+		then	PushFile "$i"
+		else	Push wc "$i"
 		fi;;
 	*)
-		PushFile "${i}";;
+		PushFile "$i";;
 	esac
 done
-if ${redirect} || ${nofile}
+if $redirect || $nofile
 then	case ${0##*/} in
 	l*)
-		eval "lzcat | ${wc}";;
+		eval "lzcat | $wc";;
 	x*)
-		eval "xzcat | ${wc}";;
+		eval "xzcat | $wc";;
 	b*)
-		eval "bzcat | ${wc}";;
+		eval "bzcat | $wc";;
 	*)
-		eval "zcat | ${wc}";;
+		eval "zcat | $wc";;
 	esac
-else	eval "${wc}"
+else	eval "$wc"
 fi
-exitstatus=${?}
+exitstatus=$?
 process=
